### ISSUE TITLE
PICKS

### ISSUE THREAD

**Issue by jrue00** [gglass/pickatron2000#1]
Hey, awesome work,is there way you could post the picks without having to run everything myself. I am curious on how the predictions stack up versus the actual scores

**Comment by gglass** [comment]
Sure! I'll start uploading the picks I end up going with week to week. I can try to get that in later today.

**Comment by gglass** [comment]
I've just uploaded a summary of the picks for week 4. I'll start doing this week to week as the season goes on.

**Comment by jrue00** [comment]
awesome thanks. yea, Im doing a school project right now for my stats class and I choose to write about NFL prediction variables and what seems to have the most impact or weight when it comes to predicting scores, spread, overs...etc so I appreciate it a lot

**Comment by jrue00** [comment]
Also one more quick question, which team do you have covering the spread. Is the away team favorited when it is a positive or negative value.

**Comment by gglass** [comment]
So the spread will always be expressed as AWAY - HOME. So a spread of -2.07 indicates the HOME team is expected to win by 2 points.

I'd be very interested to learn what you learn for your school project. I wrote all this stuff as a fun way to learn about bots and machine learning for a friendly competition between myself and my other developers at work. I am 100% a novice when it comes to machine learning and am figuring this all out on the fly. I'd love it if you could share some of the insights you are able to draw from this.
